# Generated by Django 3.2.3 on 2021-05-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=15)),
                ('c_id', models.IntegerField()),
                ('c_phone_no', models.BigIntegerField()),
                ('c_emailid', models.EmailField(max_length=254)),
                ('c_balance', models.FloatField()),
            ],
        ),
    ]
